### ISSUE TITLE
No working in Third-party win32 Context Menu

### ISSUE THREAD

**Issue by nullnullnullnull0** [krlvm/ContextMenuNormalizer#1]
Does SetBitmapBits only work on explorer's Context Menu? Using this code can't modify the color of other win32 Context Menu. If you directly modify the image of ImmersiveStart::Menu under aero.msstyles and use UXThemePatcher to apply the theme, you can find all win32 Context Menu has changed colors, just like StartAllBack. I tried to use this codes to modify the colors of other controls, such as Trackbar, and it worked very well.

**Comment by krlvm** [comment]
The only purpose of this code is to add contrast between File Explorer menu highlight and background, like it was in 1507-1809.
Regular Win32 menus, which have blue selection highlight on Windows 10, do not use ImmersiveStart::Menu theme.

**Comment by nullnullnullnull0** [comment]
Your another project AccentColorizer, can it modify the colors of other Win32 menus? Is there any plan to update?

**Comment by krlvm** [comment]
Yes, it, theoretically, can change Win32 menus colors, but on Windows 11 I prefer copying msstyles from the latest Insider Preview builds to get a gray highlight.

I figured out why it does not work with checkboxes and some other controls, it does not work correctly because Windows has multiple bitmaps in msstyles file, e.g. per 100% and 125% DPI scaling, and for some reason `OpenThemeData` always returns 100% DPI bitmaps, while SAB does not have that issue, so I don't know.
